### ISSUE TITLE
Switch to Vite

### ISSUE THREAD

**Issue by driesvints** [laravelio/paste.laravel.io#118]
Similar to https://github.com/laravelio/laravel.io/pull/882

**Comment by thinkverse** [comment]
Started work on this and found an issue where `highlightjs-line-numbers.js` doesn't work with Vite's ES6 modules. This is due to it being restricted to CommonJS (https://github.com/wcoder/highlightjs-line-numbers.js/issues/78).

A potential workaround is using a CDN like Cloudflare and loading it after `app.js`. Or switching to another open-source free code highlighter like [Prism](https://prismjs.com/).

Any recommendations on which avenue to pursue?

**Comment by thinkverse** [comment]
Found a third option I found is to create an intermediate JavaScript file in `resources/js` that imports `highlightjs-line-numbers.js` that gets resolved after `app.js` in its own `<script>` tag. This has the same effect as using the CDN it's just it uses the npm version instead.
